
CONTACTO_EMPRESARIAL                                                                                                                                   EMPRESA                                                                                                                                                TOTAL_HORAS_VALIDADAS
------------------------------------------------------------------------------------------------------------------------------------------------------ ------------------------------------------------------------------------------------------------------------------------------------------------------ ---------------------
Ana Morales                                                                                                                                            TechNova Solutions                                                                                                                                                        16
Mario Pineda                                                                                                                                           FinTech Guatemala                                                                                                                                                         16
Sofía Valdez                                                                                                                                           Agropecuaria El Sol                                                                                                                                                       16
Carlos Fuentes                                                                                                                                         Industrias La Aurora                                                                                                                                                      14
Diana Rosales                                                                                                                                          FinTech Guatemala                                                                                                                                                          6

