
CARNE                NOMBRE_COMPLETO                                                                                                                                        EMPRESA                                                                                                                                                ESPECIALIDAD_TECNICA                                                                                                                                  
-------------------- ------------------------------------------------------------------------------------------------------------------------------------------------------ ------------------------------------------------------------------------------------------------------------------------------------------------------ ------------------------------------------------------------------------------------------------------------------------------------------------------
2024001              Diego López                                                                                                                                            TechNova Solutions                                                                                                                                     Desarrollo de Software Web                                                                                                                            
2024002              María Aguilar                                                                                                                                          Industrias La Aurora                                                                                                                                   Mantenimiento Eléctrico Industrial                                                                                                                    
2024004              Sara Pinzón                                                                                                                                            Servicios Contables GT                                                                                                                                 Asistente Contable y Auditoría                                                                                                                        
2024005              Fernando Cruz                                                                                                                                          Agropecuaria El Sol                                                                                                                                    Mantenimiento de Maquinaria Agrícola                                                                                                                  
2024007              Andrés Barrios                                                                                                                                         FinTech Guatemala                                                                                                                                      Desarrollador Backend Junior                                                                                                                          

